#!/bin/sh
# Load kernel modules listed in /etc/modules

case "$1" in
	start)
		if [ -f /etc/modules ]; then
			while read -r module args; do
				case "$module" in
					''|\#*) continue ;;
				esac
				modprobe "$module" $args 2>/dev/null
			done < /etc/modules
		fi
		;;
	stop|restart|reload)
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
