#!/bin/sh

case "$1" in
	start)
		echo "Configuring piclock network"
		(/opt/clock8002/piclock-network.sh) &
		;;
	stop)
		true
		;;
	restart|reload)
		"$0" stop
		"$0" start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
