#!/bin/sh
# Start Dropbear SSH daemon with persisted host keys from /root/ssh.
# Host keys are placed there by S49sshd-keys before this script runs.

DAEMON="dropbear"
PIDFILE="/var/run/dropbear.pid"
KEY_DIR="/root/ssh"

start() {
	printf "Starting %s: " "$DAEMON"
	/usr/sbin/dropbear \
		-r "$KEY_DIR/dropbear_rsa_hostkey" \
		-r "$KEY_DIR/dropbear_ed25519_hostkey" \
		-p 22 \
		-P "$PIDFILE"
	echo "OK"
}

stop() {
	printf "Stopping %s: " "$DAEMON"
	start-stop-daemon --stop --pidfile "$PIDFILE" \
		--exec /usr/sbin/dropbear
	echo "OK"
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		stop
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
