#!/bin/sh

start() {
	if [ -e "/boot/enable_clock" ]; then
		echo "Starting clock..."
		sleep 1
		/root/clock_pokemon.sh start &
	fi
}

stop() {
	true
}

restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit $?
