#!/bin/sh

SERVICE="alsa-ltc"
BIN_FILE="alsa-ltc"
CMD_FILE="alsa-ltc_cmd.sh"
POKEMON_FILE="alsa-ltc_pokemon.sh"

start() {
	echo "Setting up $SERVICE configuration"
        sleep 5
	mkdir /boot
        if [ -e  /dev/mmcblk0p1 ]; then
		mount -r /dev/mmcblk0p1 /boot
        else
		mount -r /dev/mmcblk0 /boot
        fi
	if [ -e "/boot/$BIN_FILE" ]; then
                echo "Copying $SERVICE binary"
                mkdir -p /root
                cp /boot/$BIN_FILE /root/
		chmod a+x /root/$BIN_FILE
        fi
	if [ -e "/boot/$CMD_FILE" ]; then
		echo "Copying $SERVICE configuration"
		mkdir -p /root
		cp /boot/$CMD_FILE /root/
		chmod a+x /root/$CMD_FILE
	fi
        if [ -e "/boot/$POKEMON_FILE" ]; then
                echo "Copying $SERVICE pokemon configuration"
                mkdir -p /root
                cp /boot/$POKEMON_FILE /root/
                chmod a+x /root/$POKEMON_FILE
        fi
}

stop() {
	true
}

restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
	;;
	restart|reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
