#!/bin/sh

INTERFACES_FILE="/boot/interfaces"
HOSTNAME_FILE="/boot/hostname"
CLOCK_FILE="/boot/sdl-clock"
CLOCK_CMD="/boot/clock_cmd.sh"
CLOCK_POKEMON="/boot/clock_pokemon.sh"
NTP_CONF="/boot/ntp.conf"

start() {
	echo "Setting up clock configuration"
        sleep 5
	mkdir /boot
        if [ -e  /dev/mmcblk0p1 ]; then
		mount -r /dev/mmcblk0p1 /boot
        else
		mount -r /dev/mmcblk0 /boot
        fi
        if [ -e "$INTERFACES_FILE" ]; then
                echo "Copying network settings"
                cp $INTERFACES_FILE /etc/network/interfaces
        fi
        if [ -e "$HOSTNAME_FILE" ]; then
                echo "Setting hostname"
		cat $HOSTNAME_FILE
		hostname `cat $HOSTNAME_FILE`
                cp $HOSTNAME_FILE /etc/hostname
        fi
	if [ -e "$CLOCK_FILE" ]; then
                echo "Copying clock binary"
                mkdir -p /root
                cp $CLOCK_FILE /root/sdl-clock
		chmod a+x /root/sdl-clock
        fi
	if [ -e "$CLOCK_CMD" ]; then
		echo "Copying clock configuration"
		mkdir -p /root
		cp $CLOCK_CMD /root/clock_cmd.sh
		chmod a+x /root//clock_cmd.sh
	fi
        if [ -e "$CLOCK_POKEMON" ]; then
                echo "Copying clock pokemon configuration"
                mkdir -p /root
                cp $CLOCK_POKEMON /root/clock_pokemon.sh
                chmod a+x /root/clock_pokemon.sh
        fi
	if [ -e "$NTP_CONF" ]; then
		echo "Copying ntp configuration"
		cp $NTP_CONF /etc/ntp.conf
	fi
}

stop() {
	true
}

restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
	;;
	restart|reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
